# Generated by Django 2.2.6 on 2019-10-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='streetAddress',
            field=models.CharField(blank=True, max_length=40),
        ),
    ]
